version: '3.8'

services:
  app:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - .:/app
      - ./openai-assistant-api/.streamlit/secrets.toml:/app/.streamlit/secrets.toml
    environment:
      - PYTHONUNBUFFERED=1
